name: solitar
services:
  solitar:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    container_name: solitar
    ports:
      - "127.0.0.1:8080:8080"
    env_file: ./apps/backend/.env.docker-compose
    volumes:
      - solitar-data:/tmp/solitar
    depends_on:
      scylla_db:
        condition: service_healthy
      redis:
        condition: service_healthy

  kgs:
    build:
      context: .
      dockerfile: ./apps/kgs/Dockerfile
    container_name: kgs
    ports:
      - "127.0.0.1:8081:8081"
    env_file: ./apps/kgs/.env.docker-compose
    volumes:
      - kgs-service-data:/tmp/kgs
    depends_on:
      kgs_db:
        condition: service_healthy

  redis:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: solitar-redis
    restart: on-failure
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 3s
      timeout: 5s
      retries: 3

  kgs_db:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: kgs-db
    restart: on-failure
    ports:
      - "127.0.0.1:6380:6379"
    volumes:
      - kgs-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 3s
      timeout: 5s
      retries: 3
    command: >
      dragonfly
      --logtostderr
      --dir my-snapshot-dir
      --dbfilename my-snapshot-file-{timestamp}
      --snapshot_cron "*/5 * * * *"

  scylla_db:
    image: scylladb/scylla
    container_name: scylla-db
    restart: on-failure
    ports:
      - "127.0.0.1:9042:9042"
    volumes:
      - scylla-data:/var/lib/scylla
    command: >
      --memory 2G
      --smp 1
      --overprovisioned 1
      --developer-mode 1

  rabbitmq:
    image: rabbitmq:4.3.1-management-alpine
    container_name: solitar-rabbitmq
    restart: on-failure
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: solitar
      RABBITMQ_DEFAULT_PASS: solitar

volumes:
  solitar-data:
  redis-data:
  kgs-data:
  scylla-data:
  rabbitmq-data:
  kgs-service-data:
