spring:
  application:
    name: solitar
  main:
    banner-mode: off
  profiles:
    default: prod
  data:
    redis:
      url: ${BACKEND_REDIS_URL}
  cassandra:
    contact-points: ${CASSANDRA_CONTACT_POINTS:localhost:9042}
    keyspace-name: ${CASSANDRA_KEYSPACE:solitar}
    local-datacenter: ${CASSANDRA_LOCAL_DATACENTER:datacenter1}
    schema-action: create_if_not_exists
  rabbitmq:
    host: ${RABBITMQ_URL:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}

server:
  forward-headers-strategy: framework
  port: ${BACKEND_SERVER_PORT:8080}

app:
  kgs-endpoint: http://localhost:8081
